# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weedshop' do
 use_frameworks!
 pod 'Fabric'
 pod 'Crashlytics'
 pod 'Alamofire', '~> 4.0’
 pod 'SkyFloatingLabelTextField', '~> 2.0.0'
 pod 'TGLParallaxCarousel'
 pod 'SDWebImage/WebP'
 pod 'GoogleMaps'
 pod 'GooglePlaces'
 pod "KRProgressHUD"
 pod 'GLNotificationBar'
end
